### ISSUE TITLE
Problem upgrading dependencies to use latest Rx

### ISSUE THREAD

**Issue by mandricore** [asterjs/aster-src#2]
```bash
  ✓ can register parsers
  ✓ works (250ms)
  1) works for explicit list of files

  2 passing (260ms)
  1 failing

  1)  works for explicit list of files:
     TypeError: source.subscribe is not a function
      at ZipObservable.subscribeCore (node_modules/rx/dist/rx.js:4186:34)
      at ZipObservable.tryCatcher (node_modules/rx/dist/rx.js:63:31)
      at Rx.internals.ScheduledItem.setDisposable [as action] (node_modules/rx/dist/rx.js:2082:46)
      at Rx.internals.ScheduledItem.ScheduledItem.invokeCore (node_modules/rx/dist/rx.js:896:33)
      at Rx.internals.ScheduledItem.ScheduledItem.invoke (node_modules/rx/dist/rx.js:884:40)
      at runTrampoline (node_modules/rx/dist/rx.js:1125:37)
      at tryCatcher (node_modules/rx/dist/rx.js:63:31)
      at CurrentThreadScheduler.schedule (node_modules/rx/dist/rx.js:1141:45)
      at ZipObservable.Rx.ObservableBase.ObservableBase._subscribe (node_modules/rx/dist/rx.js:2095:32)
      at ZipObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (node_modules/rx/dist/rx.js:2034:19)
      at Context.<anonymous> (test/test.js:45:3)
```

The problem is with the `.subscribe` call

```js
	src(files, {noglob: true})
	.concatAll()
	.zip(files, function (file, fileName) {
		assert.equal(file.loc.source, fileName);
		assert.equal(file.program.type, 'Program');
	})
	.subscribe(function () {}, done, done);
```

Which is a `ZipObservable`

```js
zipped ZipObservable {
  _s: 
   [ MergeObservable { source: [Object], maxConcurrent: 1 },
     'glob.js',
     'index.js',
     'test/test.js' ],
  _cb: [Function] }
```

Which I think is defined here [ZipObservable.subscribeCore](https://github.com/Reactive-Extensions/RxJS/blob/master/src/modular/observable/zip.js#L72)

but doesn't work just substituting for `subscribeCore` however... it inherits from `ObservableBase` via `inherits(ZipObservable, ObservableBase);` so...

[observablebase](https://github.com/Reactive-Extensions/RxJS/blob/master/src/modular/observable/observablebase.js#L31) has a `_subscribe` method.

Any advice would be great to help resolve this. On another note, I would like to make this `-src` thing more generic, able to take any stream not only a file stream. Perhaps making the src map and then delegate the incoming observed file to an observable stream src handler.
Your thoughts?

**Comment by mandricore** [comment]
I "fixed" by uncommenting the `.zip` part. Also added a new `srcObserver` option which allows fully customizing how you create or set  the observable used to observe the javascript sources
